<script setup lang="ts">
import FundingCategorySelector from '@/components/reports/FundingCategorySelector.vue';
import FundingProgramTables from '@/components/reports/FundingProgramTables.vue';
import ReportChartBlock from '@/components/reports/ReportChartBlock.vue';
import ReportMetricsGrid from '@/components/reports/ReportMetricsGrid.vue';
import { fundingStats, hasBreakdownData, hasJobsData, jobsBySex, programMetricTotals } from '@/composables/useFundingGroup';
import { formatFundingOrEmpty } from '@/helpers/formatCurrency';
import type { FundingCategorySummaryData } from '@/types/reports';
import { computed, defineAsyncComponent } from 'vue';

const FundingSplitChart = defineAsyncComponent(() => import('@/components/charts/FundingSplitChart.vue'));
const JobsBreakdownHeatmap = defineAsyncComponent(() => import('@/components/charts/JobsBreakdownHeatmap.vue'));
const StackedBarBySexChart = defineAsyncComponent(() => import('@/components/charts/StackedBarBySexChart.vue'));

interface Props {
    /** Short name used in every heading here, e.g. `SETUP`. */
    label: string;
    /** Spelled-out program name, for the category selector's heading. */
    fullName: string;
    /** Report year, shown in the block descriptions. */
    year: string;
    categories: FundingCategorySummaryData[];
}

const props = defineProps<Props>();

const stats = computed(() => fundingStats(props.categories));
const metricTotals = computed(() => programMetricTotals(props.categories));
const jobs = computed(() => jobsBySex(props.categories));
</script>

<template>
    <div class="space-y-3 md:space-y-4">
        <ReportMetricsGrid
            five-up
            :metrics="[
                { label: 'Categories', value: categories.length },
                { label: 'Total Projects', value: stats.totalProjects },
                { label: 'Total Funding', value: formatFundingOrEmpty(stats.totalAmount), valueClass: 'text-base md:text-lg' },
                { label: 'Male-led Projects', value: stats.maleProjects },
                { label: 'Female-led Projects', value: stats.femaleProjects },
            ]"
        />

        <ReportMetricsGrid
            v-if="metricTotals.hasData"
            :metrics="[
                { label: 'Funded Projects', value: metricTotals.fundedProjects },
                {
                    label: 'Value Funded',
                    value: formatFundingOrEmpty(metricTotals.fundedValue),
                    valueClass: 'text-base md:text-lg',
                },
                { label: 'Training Participants', value: metricTotals.trainingParticipants },
                { label: 'Jobs Generated', value: metricTotals.jobsGenerated },
            ]"
        />

        <FundingCategorySelector
            :title="fullName"
            :description="`Select category to preview chart • ${year}`"
            :empty-description="`No category data yet for ${year}`"
            :categories="categories"
            v-slot="{ category }"
        >
            <FundingSplitChart :data="category" :title="category.label" />
        </FundingCategorySelector>

        <ReportChartBlock v-if="hasJobsData(jobs)" :title="`${label} Jobs Generated by Sex`" :description="`Jobs generated per category • ${year}`">
            <StackedBarBySexChart :data="jobs" axis-title="Jobs Generated" />
        </ReportChartBlock>

        <ReportChartBlock
            v-if="hasBreakdownData(categories)"
            :title="`${label} Jobs Breakdown`"
            description="Overlapping groups within the jobs generated — read each cell on its own, not as a share of the total"
        >
            <JobsBreakdownHeatmap :categories="categories" />
        </ReportChartBlock>

        <FundingProgramTables :group-label="label" :categories="categories" :empty-label="`No ${label} category data yet.`" />
    </div>
</template>
