import type { FundingCategorySummaryData } from '@/types/reports';
import { mount } from '@vue/test-utils';
import { describe, expect, it, vi } from 'vitest';

/*
 * The charts are ApexCharts components loaded through `defineAsyncComponent`,
 * which happy-dom cannot render and whose import would otherwise still be in
 * flight when the environment tears down. Stubbing them at the module boundary
 * leaves the panel's own decisions — which blocks render, how totals read — as
 * the thing under test.
 */
const chartStub = () => ({
    __esModule: true,
    default: { name: 'ChartStub', template: '<div class="chart-stub" />' },
});

// Declared inside each factory: `vi.mock` is hoisted above any top-level const
// it would otherwise close over.
vi.mock('@/components/charts/FundingSplitChart.vue', () => chartStub());
vi.mock('@/components/charts/JobsBreakdownHeatmap.vue', () => chartStub());
vi.mock('@/components/charts/StackedBarBySexChart.vue', () => chartStub());

import FundingGroupPanel from './FundingGroupPanel.vue';

const category = (overrides: Partial<FundingCategorySummaryData> = {}): FundingCategorySummaryData => ({
    label: 'GIA ZSP',
    slug: 'gia-zsp',
    maleProjects: 0,
    maleAmount: 0,
    femaleProjects: 0,
    femaleAmount: 0,
    ...overrides,
});

const mountPanel = (categories: FundingCategorySummaryData[], label = 'GIA') =>
    mount(FundingGroupPanel, {
        props: { label, fullName: 'Grants-in-Aid (GIA)', year: '2025', categories },
    });

describe('FundingGroupPanel', () => {
    it('labels every heading with the family it was given', () => {
        const wrapper = mountPanel([category({ jobsFemale: 3, jobsMale: 2, jobsPwd: 1 })], 'SETUP');

        const text = wrapper.text();
        expect(text).toContain('SETUP Jobs Generated by Sex');
        expect(text).toContain('SETUP Jobs Breakdown');
    });

    it('totals projects and funding across the categories it was given', () => {
        const wrapper = mountPanel([
            category({ slug: 'gia-zsp', maleProjects: 2, femaleProjects: 3, maleAmount: 1000, femaleAmount: 500 }),
            category({ slug: 'gia-zds', maleProjects: 1, femaleProjects: 4, maleAmount: 250, femaleAmount: 250 }),
        ]);

        const text = wrapper.text();
        expect(text).toContain('Total Projects');
        expect(text).toContain('10');
        expect(text).toContain('2,000');
    });

    it('reads funding that was never recorded as absent, not as a nil balance', () => {
        const wrapper = mountPanel([category()]);

        expect(wrapper.text()).toContain('No data yet');
    });

    it('hides the program metrics row until a metric is entered', () => {
        // These columns default to zero, so an all-zero row means "never
        // entered" and printing it would assert a figure nobody recorded.
        expect(mountPanel([category({ maleProjects: 4 })]).text()).not.toContain('Training Participants');
        expect(mountPanel([category({ trainingParticipants: 12 })]).text()).toContain('Training Participants');
    });

    it('hides the jobs charts until the jobs behind them are entered', () => {
        const empty = mountPanel([category({ maleProjects: 4 })]);

        expect(empty.text()).not.toContain('Jobs Generated by Sex');
        expect(empty.text()).not.toContain('Jobs Breakdown');
    });

    it('draws the by-sex chart on jobs alone, and the breakdown only on a recorded subset', () => {
        const jobsOnly = mountPanel([category({ jobsFemale: 5, jobsMale: 4 })]);

        expect(jobsOnly.text()).toContain('Jobs Generated by Sex');
        expect(jobsOnly.text()).not.toContain('Jobs Breakdown');
    });
});
