<script setup lang="ts">
import FundingCategorySelector from '@/components/reports/FundingCategorySelector.vue';
import FundingProgramTables from '@/components/reports/FundingProgramTables.vue';
import ReportChartBlock from '@/components/reports/ReportChartBlock.vue';
import ReportMetricsGrid from '@/components/reports/ReportMetricsGrid.vue';
import ReportStoryLead from '@/components/reports/ReportStoryLead.vue';
import { fundingStats, hasBreakdownData, hasJobsData, jobsBySex, programMetricTotals } from '@/composables/useFundingGroup';
import { formatFundingOrEmpty } from '@/helpers/formatCurrency';
import { fundingGroupLead, jobsBreakdownTakeaway, peakRowTakeaway, sexShareTakeaway } from '@/helpers/reportStory';
import type { FundingCategorySummaryData } from '@/types/reports';
import { computed, defineAsyncComponent } from 'vue';

const FundingSplitChart = defineAsyncComponent(() => import('@/components/charts/FundingSplitChart.vue'));
const JobsBreakdownHeatmap = defineAsyncComponent(() => import('@/components/charts/JobsBreakdownHeatmap.vue'));
const StackedBarBySexChart = defineAsyncComponent(() => import('@/components/charts/StackedBarBySexChart.vue'));

interface Props {
    /** Short name used in every heading here, e.g. `SETUP`. */
    label: string;
    /** Spelled-out program name, for the category selector's heading. */
    fullName: string;
    /** Report year, shown in the block descriptions. */
    year: string;
    categories: FundingCategorySummaryData[];
}

const props = defineProps<Props>();

const stats = computed(() => fundingStats(props.categories));
const metricTotals = computed(() => programMetricTotals(props.categories));
const jobs = computed(() => jobsBySex(props.categories));

/*
 * The same two-sentence opening on all three funding tabs, so a reader who
 * has read SETUP already knows how to read CEST and GIA.
 */
const leadSentences = computed(() =>
    fundingGroupLead({
        label: props.label,
        year: props.year,
        stats: stats.value,
        metrics: metricTotals.value,
    }),
);

/**
 * Jobs split by sex is a true partition, so a share reads honestly here. The
 * PWD / senior / IP / 4Ps breakdown below it is stated one group at a time and
 * never totalled or ranked: those groups overlap.
 */
const jobsTakeaway = computed(() =>
    sexShareTakeaway(
        'the jobs generated',
        jobs.value.reduce((sum, row) => sum + row.female, 0),
        jobs.value.reduce((sum, row) => sum + row.male, 0),
    ),
);

/** Which category carried the most projects — the point of the per-category chart. */
const categoryTakeaway = computed(() =>
    peakRowTakeaway(
        props.categories.map((category) => ({ label: category.label, female: category.femaleProjects, male: category.maleProjects })),
        (label, total, tied) => (tied ? `${label} tied for the most projects (${total} each).` : `${label} had the most projects (${total}).`),
    ),
);

const breakdownTakeaway = computed(() => jobsBreakdownTakeaway(props.categories));
</script>

<template>
    <div class="space-y-3 md:space-y-4">
        <ReportStoryLead :sentences="leadSentences" />

        <ReportMetricsGrid
            five-up
            :metrics="[
                { label: 'Categories', value: categories.length },
                { label: 'Total Projects', value: stats.totalProjects },
                { label: 'Total Funding', value: formatFundingOrEmpty(stats.totalAmount), valueClass: 'text-base md:text-lg' },
                { label: 'Male-led Projects', value: stats.maleProjects },
                { label: 'Female-led Projects', value: stats.femaleProjects },
            ]"
        />

        <ReportMetricsGrid
            v-if="metricTotals.hasData"
            :metrics="[
                { label: 'Funded Projects', value: metricTotals.fundedProjects },
                {
                    label: 'Value Funded',
                    value: formatFundingOrEmpty(metricTotals.fundedValue),
                    valueClass: 'text-base md:text-lg',
                },
                { label: 'Training Participants', value: metricTotals.trainingParticipants },
                { label: 'Jobs Generated', value: metricTotals.jobsGenerated },
            ]"
        />

        <FundingCategorySelector
            :title="fullName"
            :description="`Select category to preview chart • ${year}`"
            :empty-description="`No category data yet for ${year}`"
            :categories="categories"
            :takeaway="categoryTakeaway"
            v-slot="{ category }"
        >
            <FundingSplitChart :data="category" :title="category.label" />
        </FundingCategorySelector>

        <ReportChartBlock
            v-if="hasJobsData(jobs)"
            :title="`${label} Jobs Generated by Sex`"
            :takeaway="jobsTakeaway"
            :description="`Jobs generated per category • ${year}`"
        >
            <StackedBarBySexChart :data="jobs" axis-title="Jobs Generated" />
        </ReportChartBlock>

        <ReportChartBlock
            v-if="hasBreakdownData(categories)"
            :title="`${label} Jobs Breakdown`"
            :takeaway="breakdownTakeaway"
            description="Overlapping groups within the jobs generated — read each cell on its own, not as a share of the total"
        >
            <JobsBreakdownHeatmap :categories="categories" />
        </ReportChartBlock>

        <FundingProgramTables :group-label="label" :categories="categories" :empty-label="`No ${label} category data yet.`" />
    </div>
</template>
